# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Local - Windows - Dell
  demands: agent.name -equals DELLWINLOCAL

steps:
- script: npm install
  displayName: 'Install npm'

- script: npm run start
  displayName: 'Run nest js with npm'
